version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:p123@db:5432/smartloan
      - JWT_SECRET=AWD_jwt_secret
    depends_on:
      - db

  frontend:
    image: mudithadocker/awd:phase-3-local
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p123
      POSTGRES_DB: smartloan
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: