name: Build and Deploy to AWS EC2

on:
  push:
    branches: [ phase-3 ]

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build frontend Docker image
        run: docker build --build-arg VITE_API_URL=http://localhost:3000/api -t mudithadocker/awd:phase-3-local ./frontend

      - name: Push frontend Docker image
        run: docker push mudithadocker/awd:phase-3-local

  deploy:
    needs: build-and-push-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz --exclude '.git*' -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app
            docker-compose pull frontend
            docker-compose down || true
            docker-compose up -d --build
          EOF